"""First commit

Revision ID: e32384f91547
Revises: 
Create Date: 2025-06-13 22:19:27.860827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32384f91547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('population_size', sa.Integer(), nullable=False),
    sa.Column('termination_condition', sa.String(length=50), nullable=False),
    sa.Column('termination_value', sa.Integer(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('best_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selections_id'), 'selections', ['id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('best_distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selection_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['selection_id'], ['selections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individuals_id'), 'individuals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individuals_id'), table_name='individuals')
    op.drop_table('individuals')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_selections_id'), table_name='selections')
    op.drop_table('selections')
    # ### end Alembic commands ###
